# Imports and Globals

In [14]:
import numpy as np
import pandas as pd

INPUT_FILE = "Laliga.csv"

# Question: 1
Read the data set and replace dashes with 0 to make sure you can perform arithmetic operations on the data. (2.5 points)

In [15]:
data = pd.read_csv(INPUT_FILE,skiprows=1)
data = data.replace("-",0)

data = data.apply(pd.to_numeric, errors='ignore')

print(data.dtypes)
data.shape

Pos               int64
Team             object
Seasons           int64
Points            int64
GamesPlayed       int64
GamesWon          int64
GamesDrawn        int64
GamesLost         int64
GoalsFor          int64
GoalsAgainst      int64
Champion          int64
Runner-up         int64
Third             int64
Fourth            int64
Fifth             int64
Sixth             int64
T                 int64
Debut            object
Since/LastApp    object
BestPosition      int64
dtype: object

(61, 20)

# Question: 2
Print all the teams which have started playing between 1930-1980. (5 points)

In [16]:
print(data.loc[(data["Debut"] >= "1930") & (data["Debut"] <= "1980")].Team.values)

['Valencia' 'Sevilla' 'Zaragoza' 'Real Betis' 'Deportivo La Coruna'
 'Celta Vigo' 'Valladolid' 'Sporting Gijon' 'Osasuna' 'Malaga' 'Oviedo'
 'Mallorca' 'Las Palmas' 'Granada' 'Rayo Vallecano' 'Elche' 'Hercules'
 'Tenerife' 'Murcia' 'Alaves' 'Levante' 'Salamanca' 'Sabadell' 'Cadiz'
 'Castellon' 'Cordoba' 'Recreativo' 'Burgos CF' 'Pontevedra' 'Gimnastic'
 'Alcoyano' 'Jaen' 'AD Almeria' 'Lleida' 'Condal' 'Atletico Tetuan'
 'Cultural Leonesa']

# Question: 3
Print the list of teams which came Top 5 in terms of points (2.5 points)

In [17]:
data.sort_values(by=['Points'], ascending=False)[:5][["Team", "Points"]]

              Team  Points
0      Real Madrid    4385
1        Barcelona    4262
2  Atletico Madrid    3442
3         Valencia    3386
4  Athletic Bilbao    3368

# Question: 4
Write a function with name “Goal_diff_count” which should return all the teams with their Goal Differences. Using the same function, find the team which has maximum and minimum goal difference. (5 points)

Goal_diff_count = GoalsFor - GoalsAgainst

In [18]:
def Goal_diff_count(df):
    return df["GoalsFor"]-df["GoalsAgainst"]

data["GoalDiff"] = Goal_diff_count(data)
print("Team: {} has the maximum goal difference of: {}".format(data.iloc[data["GoalDiff"].idxmax()]["Team"],
                                                               data.iloc[data["GoalDiff"].idxmax()]["GoalDiff"]))

print("Team: {} has the minium goal difference of: {}".format(data.iloc[data["GoalDiff"].idxmin()]["Team"],
                                                               data.iloc[data["GoalDiff"].idxmin()]["GoalDiff"]))

Team: Real Madrid has the maximum goal difference of: 2807
Team: Racing Santander has the minium goal difference of: -525

# Question: 5
Create a new column with name “Winning Percent” and append it to the data set (5 points)

Percentage of Winning = (GamesWon / GamesPlayed)*100

If there are any numerical error, replace it with 0%

Print the top 5 teams which has the highest Winning percentage

In [19]:
data["Winning Percent"] = (data["GamesWon"]/data["GamesPlayed"])*100
data["Winning Percent"] = data["Winning Percent"].fillna(0)
print(data["Winning Percent"])

0     59.630702
1     57.241130
2     47.475134
3     44.557057
4     43.772629
5     41.112957
6     36.100533
7     37.532580
8     35.146022
9     35.069444
10    36.797386
11    34.511190
12    31.582538
13    31.722689
14    32.304527
15    32.321700
16    31.075697
17    34.228188
18    33.704453
19    33.485401
20    41.176471
21    29.380054
22    28.987730
23    29.941003
24    32.236842
25    29.299363
26    31.376518
27    24.744027
28    32.894737
29    28.109453
        ...
31    30.281690
32    23.214286
33    27.745665
34    30.838323
35    28.148148
36    27.192982
37    29.078014
38    32.500000
39    26.881720
40    28.921569
41    29.444444
42    24.342105
43    30.701754
44    33.076923
45    22.807018
46    29.310345
47    25.000000
48    23.750000
49    27.777778
50    32.222222
51    29.166667
52    25.000000
53    33.333333
54    19.117647
55    21.052632
56    21.052632
57    23.333333
58    23.333333
59    16.666667
60     0.000000
Name: Winning Percent, Length: 61, dtype: float64

# Question: 6
Group teams based on their “Best position” and print the sum of their points for all positions (5 points)

Eg: Best Position     Points

         1                   25000

         2                    7000

In [20]:
data.groupby("BestPosition").sum()[["Points"]]

              Points
BestPosition
1              27933
2               6904
3               5221
4               6563
5               1884
6               2113
7               1186
8               1134
9                 96
10               450
11               445
12               511
14                71
15                14
16                81
17               266
19                81
20                34